//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiPoints.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BiPoints.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add failed.
        /// </summary>
        internal static string ErrorAddFailed {
            get {
                return ResourceManager.GetString("ErrorAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate. Scan another code.
        /// </summary>
        internal static string ErrorDuplicate {
            get {
                return ResourceManager.GetString("ErrorDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get data failed.
        /// </summary>
        internal static string ErrorGetDataFailed {
            get {
                return ResourceManager.GetString("ErrorGetDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data.
        /// </summary>
        internal static string ErrorInvalidData {
            get {
                return ResourceManager.GetString("ErrorInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection to the server.
        /// </summary>
        internal static string ErrorNoConnectionToTheServer {
            get {
                return ResourceManager.GetString("ErrorNoConnectionToTheServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed.
        /// </summary>
        internal static string ErrorRegistrationFailed {
            get {
                return ResourceManager.GetString("ErrorRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan failed. Incorrect QR code.
        /// </summary>
        internal static string ErrorScanFailed {
            get {
                return ResourceManager.GetString("ErrorScanFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should contain 3 char.
        /// </summary>
        internal static string ErrorShouldContain3Char {
            get {
                return ResourceManager.GetString("ErrorShouldContain3Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item doesnt exist.
        /// </summary>
        internal static string ErrorTheItemDoesntExist {
            get {
                return ResourceManager.GetString("ErrorTheItemDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user doesnt exist.
        /// </summary>
        internal static string ErrorTheUserDoesntExist {
            get {
                return ResourceManager.GetString("ErrorTheUserDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user already exist.
        /// </summary>
        internal static string ErrorThisUserAlreadyExist {
            get {
                return ResourceManager.GetString("ErrorThisUserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password.
        /// </summary>
        internal static string ErrorWrongUsernameOrPassword {
            get {
                return ResourceManager.GetString("ErrorWrongUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in one day.
        /// </summary>
        internal static string SmallStringInOneDay {
            get {
                return ResourceManager.GetString("SmallStringInOneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        internal static string StringAchievements {
            get {
                return ResourceManager.GetString("StringAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string StringAlreadyHaveAnAccount {
            get {
                return ResourceManager.GetString("StringAlreadyHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string StringClose {
            get {
                return ResourceManager.GetString("StringClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For use.
        /// </summary>
        internal static string StringForUse {
            get {
                return ResourceManager.GetString("StringForUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get.
        /// </summary>
        internal static string StringGet {
            get {
                return ResourceManager.GetString("StringGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get points.
        /// </summary>
        internal static string StringGetPoints {
            get {
                return ResourceManager.GetString("StringGetPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        internal static string StringLastname {
            get {
                return ResourceManager.GetString("StringLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string StringLogin {
            get {
                return ResourceManager.GetString("StringLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string StringName {
            get {
                return ResourceManager.GetString("StringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string StringPassword {
            get {
                return ResourceManager.GetString("StringPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product scanned correctly.
        /// </summary>
        internal static string StringProductScannedCorrectly {
            get {
                return ResourceManager.GetString("StringProductScannedCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string StringScan {
            get {
                return ResourceManager.GetString("StringScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan failed.
        /// </summary>
        internal static string StringScanFailed {
            get {
                return ResourceManager.GetString("StringScanFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning.
        /// </summary>
        internal static string StringScanning {
            get {
                return ResourceManager.GetString("StringScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the QR code.
        /// </summary>
        internal static string StringScanTheQrCode {
            get {
                return ResourceManager.GetString("StringScanTheQrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up!.
        /// </summary>
        internal static string StringSignUp {
            get {
                return ResourceManager.GetString("StringSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        internal static string StringUsed {
            get {
                return ResourceManager.GetString("StringUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string StringUsername {
            get {
                return ResourceManager.GetString("StringUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string StringWelcome {
            get {
                return ResourceManager.GetString("StringWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your points.
        /// </summary>
        internal static string StringYourPoints {
            get {
                return ResourceManager.GetString("StringYourPoints", resourceCulture);
            }
        }
    }
}
